const accountUser = window.cafeStorage?.read("cafe-creme-current-user", null) || null;
if (!accountUser) window.location.href = "login.html";
else {
  const form = document.querySelector("#account-form"); const status = document.querySelector("#account-status"); const address = document.querySelector("#account-address");
  form.name.value = accountUser.name || ""; form.email.value = accountUser.email || ""; form.phone.value = accountUser.phone || "";
  const savedAddress = window.cafeStorage?.read("cafe-creme-saved-address", null) || null; if (savedAddress?.address) address.textContent = savedAddress.address;
  form.addEventListener("submit", (event) => { event.preventDefault(); const details = Object.fromEntries(new FormData(form)); const users = (window.cafeStorage?.read("cafe-creme-users", []) || []).map((user) => user.email === accountUser.email ? { ...user, name: details.name, phone: details.phone } : user); const updated = { ...accountUser, name: details.name, phone: details.phone }; window.cafeStorage?.write("cafe-creme-users", users); window.cafeStorage?.write("cafe-creme-current-user", updated); status.textContent = "Profile saved."; status.className = "alert alert-success mt-3"; });
  const locationPanel = document.createElement("section"); locationPanel.className = "account-location-panel"; locationPanel.innerHTML = `<div><p class="cafe-eyebrow">Delivery location</p><h2>Where should we bring it?</h2><p class="account-location-help">Save one address for faster checkout. You can change it anytime.</p></div><form id="account-location-form"><label class="form-label" for="account-location-input">Address</label><textarea class="form-control" id="account-location-input" name="address" rows="2" placeholder="Flat, building, street, area" required></textarea><label class="form-label" for="account-landmark-input">Landmark <span class="text-muted fw-normal">(optional)</span></label><input class="form-control" id="account-landmark-input" name="landmark" placeholder="Near..." /><div class="account-location-actions"><button class="btn btn-dark" type="submit">Save location</button><button class="btn btn-outline-dark" id="account-use-location" type="button"><i class="fa-solid fa-location-crosshairs" aria-hidden="true"></i> Use current location</button></div><output id="account-location-status"></output></form>`; document.querySelector(".account-shortcuts")?.append(locationPanel);
  const locationForm = document.querySelector("#account-location-form"); const locationInput = document.querySelector("#account-location-input"); const landmarkInput = document.querySelector("#account-landmark-input"); const locationStatus = document.querySelector("#account-location-status");
  if (savedAddress) { locationInput.value = savedAddress.address || ""; landmarkInput.value = savedAddress.landmark || ""; }
  locationForm.addEventListener("submit", (event) => { event.preventDefault(); const details = Object.fromEntries(new FormData(locationForm)); const saved = { ...savedAddress, address: details.address.trim(), landmark: details.landmark.trim() }; localStorage.setItem("cafe-creme-saved-address", JSON.stringify(saved)); address.textContent = saved.address; locationStatus.textContent = "Delivery location saved."; locationStatus.className = "alert alert-success mt-2"; });
  document.querySelector("#account-use-location").addEventListener("click", () => { if (!navigator.geolocation) { locationStatus.textContent = "Location is not supported here. Enter your address manually."; locationStatus.className = "alert alert-warning mt-2"; return; } locationStatus.textContent = "Finding your location..."; navigator.geolocation.getCurrentPosition(({ coords }) => { const saved = { ...savedAddress, address: `GPS location (${coords.latitude.toFixed(4)}, ${coords.longitude.toFixed(4)})`, landmark: landmarkInput.value.trim(), latitude: coords.latitude, longitude: coords.longitude }; localStorage.setItem("cafe-creme-saved-address", JSON.stringify(saved)); locationInput.value = saved.address; address.textContent = "Current location"; locationStatus.textContent = "Current location saved."; locationStatus.className = "alert alert-success mt-2"; }, () => { locationStatus.textContent = "We could not access your location. Enter your address manually."; locationStatus.className = "alert alert-warning mt-2"; }, { enableHighAccuracy: true, timeout: 10000, maximumAge: 300000 }); });
}
