const menuContainer = document.querySelector("#menu-categories");
const searchInput = document.querySelector("#menu-search");
const initialMenuSearch = new URLSearchParams(window.location.search).get("search");
if (initialMenuSearch) searchInput.value = initialMenuSearch;
const filtersContainer = document.querySelector("#menu-filters");
const resultCount = document.querySelector("#menu-result-count");
const cartKey = "cafe-creme-cart";
const cartOptionsKey = "cafe-creme-cart-options";
const festivalFeature = document.querySelector("#festival-menu-feature");
const menuModalElement = document.querySelector("#menu-item-modal");
const menuModal = menuModalElement && window.bootstrap ? new bootstrap.Modal(menuModalElement) : null;
const menuCartSummary = document.querySelector("#menu-cart-summary");
const pendingCoupon = new URLSearchParams(window.location.search).get("coupon");
if (pendingCoupon) localStorage.setItem("cafe-creme-pending-coupon", pendingCoupon.toUpperCase());
let modalItemId = "";
let activeCategory = "All";
let selectedModalOptions = {};

function escapeHtml(value = "") { const node = document.createElement("div"); node.textContent = String(value); return node.innerHTML; }
function getCart() { return JSON.parse(localStorage.getItem(cartKey) || "{}"); }
function getCartOptions() { return JSON.parse(localStorage.getItem(cartOptionsKey) || "{}"); }
function menuPrice(item) { const options = getCartOptions()[item.id] || {}; return item.price + (options.size === "Large" ? 40 : 0) + (options.extraShot ? 35 : 0); }
function showMenuToast(message) { let toast = document.querySelector("#menu-toast"); if (!toast) { toast = document.createElement("div"); toast.id = "menu-toast"; toast.className = "menu-toast"; toast.setAttribute("role", "status"); document.body.appendChild(toast); } toast.textContent = message; toast.classList.add("is-visible"); clearTimeout(showMenuToast.timer); showMenuToast.timer = setTimeout(() => toast.classList.remove("is-visible"), 2200); }
function updateCartCount() { const cart = getCart(); const count = Object.values(cart).reduce((total, quantity) => total + quantity, 0); const badge = document.querySelector("#cart-count"); if (badge) badge.textContent = count; if (menuCartSummary) { menuCartSummary.classList.toggle("is-visible", count > 0); document.querySelector("#menu-cart-items").textContent = `${count} item${count === 1 ? "" : "s"}`; document.querySelector("#menu-cart-total").textContent = formatCurrency(getMenuItems().reduce((total, item) => total + menuPrice(item) * (cart[item.id] || 0), 0)); } }
function updateMenuQuantityControl(id) { const item = getMenuItems().find((entry) => entry.id === id); const trigger = [...menuContainer.querySelectorAll("[data-quantity-id]")].find((element) => element.dataset.quantityId === id); const action = trigger?.closest(".menu-item-action"); if (!item || !action) return; const quantity = getCart()[id] || 0; action.innerHTML = `<strong>${formatCurrency(item.price)}</strong>${quantity ? `<div class="menu-quantity" aria-label="${escapeHtml(item.name)} quantity"><button type="button" data-quantity-id="${item.id}" data-change="-1">-</button><span>${quantity}</span><button type="button" data-quantity-id="${item.id}" data-change="1">+</button></div>` : `<button class="btn btn-dark btn-sm" type="button" data-quantity-id="${item.id}" data-change="1">Add</button>`}`; }
function changeCartQuantity(id, change, options = null) { if (change > 0 && localStorage.getItem("cafe-creme-store-open") === "false") { showMenuToast("Online ordering is currently paused"); return; } const cart = getCart(); const savedOptions = getCartOptions(); const next = (cart[id] || 0) + change; if (next <= 0) { delete cart[id]; delete savedOptions[id]; } else { cart[id] = next; if (options) savedOptions[id] = options; } localStorage.setItem(cartKey, JSON.stringify(cart)); localStorage.setItem(cartOptionsKey, JSON.stringify(savedOptions)); updateCartCount(); updateMenuQuantityControl(id); if (change > 0) { const item = getMenuItems().find((entry) => entry.id === id); if (item) showMenuToast(`${item.name} added to your cart`); } }
function removeUnavailableCartItems(items) { const ids = new Set(items.map((item) => item.id)); const cart = getCart(); let changed = false; Object.keys(cart).forEach((id) => { if (!ids.has(id)) { delete cart[id]; changed = true; } }); if (changed) localStorage.setItem(cartKey, JSON.stringify(cart)); updateCartCount(); }
function renderFilters(items) { const categories = ["All", ...new Set(items.map((item) => item.category))]; filtersContainer.innerHTML = categories.map((category) => `<button class="menu-filter ${category === activeCategory ? "is-active" : ""}" type="button" data-category="${escapeHtml(category)}">${escapeHtml(category)}</button>`).join(""); }
function setupCustomisationPanel() { if (!menuModalElement || document.querySelector("#menu-customisation")) return; const action = document.querySelector("#menu-modal-add")?.closest(".d-flex"); if (!action) return; const panel = document.createElement("div"); panel.id = "menu-customisation"; panel.className = "menu-customisation"; panel.innerHTML = `<div class="menu-customisation-heading"><strong>Make it yours</strong><small>Choose options before adding</small></div><label>Size<select id="custom-size"><option value="Regular">Regular</option><option value="Large">Large (+${formatCurrency(40)})</option></select></label><label>Milk<select id="custom-milk"><option>Whole milk</option><option>Oat milk</option><option>Almond milk</option></select></label><label class="custom-check"><input id="custom-shot" type="checkbox" /> Extra espresso shot (+${formatCurrency(35)})</label>`; action.parentElement.insertBefore(panel, action); panel.addEventListener("change", () => { selectedModalOptions = { size: panel.querySelector("#custom-size").value, milk: panel.querySelector("#custom-milk").value, extraShot: panel.querySelector("#custom-shot").checked }; const item = getMenuItems().find((entry) => entry.id === modalItemId); const extra = selectedModalOptions.size === "Large" ? 40 : 0; const shot = selectedModalOptions.extraShot ? 35 : 0; if (item) document.querySelector("#menu-modal-price").textContent = formatCurrency(item.price + extra + shot); }); }
function renderMenuPage() { const available = getMenuItems().filter((item) => item.isAvailable); removeUnavailableCartItems(available); const cart = getCart(); const term = searchInput.value.trim().toLowerCase(); const activeFestival = document.body.dataset.festival; const campaign = activeFestival && window.festivalCampaigns?.[activeFestival]; if (campaign && festivalFeature) { festivalFeature.className = "festival-menu-feature"; festivalFeature.innerHTML = `<div><strong>${escapeHtml(campaign.offer)}</strong><p>${escapeHtml(campaign.note)} ${escapeHtml(campaign.discount)} with ${escapeHtml(campaign.coupon)}.</p></div><a class="btn btn-dark btn-sm" href="offers.html">View offer</a>`; } const items = available.filter((item) => (activeCategory === "All" || item.category === activeCategory) && `${item.name} ${item.description} ${item.category}`.toLowerCase().includes(term)); const groups = items.reduce((result, item) => { (result[item.category] ||= []).push(item); return result; }, {}); renderFilters(available); resultCount.textContent = items.length ? `${items.length} item${items.length === 1 ? "" : "s"} available` : "No items match your search."; menuContainer.innerHTML = Object.entries(groups).map(([category, group]) => `<div class="col-lg-6"><section class="menu-group"><div class="menu-group-heading"><h2>${escapeHtml(category)}</h2><span>Fresh today</span></div>${group.map((item) => `<article class="menu-item" data-item-id="${item.id}">${item.image ? `<img class="menu-item-image" src="${escapeHtml(item.image)}" alt="${escapeHtml(item.name)}" loading="lazy" />` : ""}<div class="menu-item-copy"><div class="menu-item-title"><h3>${escapeHtml(item.name)}</h3>${item.isPopular ? `<span class="menu-badge">Popular</span>` : ""}</div><p>${escapeHtml(item.description)}</p><small class="dietary-label">${escapeHtml(item.dietary)}</small><small class="menu-meta">Rating ${Number(item.rating || 4.7).toFixed(1)} / ${escapeHtml(item.prepTime || "10 min")}</small></div><div class="menu-item-action"><strong>${formatCurrency(item.price)}</strong>${cart[item.id] ? `<div class="menu-quantity" aria-label="${escapeHtml(item.name)} quantity"><button type="button" data-quantity-id="${item.id}" data-change="-1">-</button><span>${cart[item.id]}</span><button type="button" data-quantity-id="${item.id}" data-change="1">+</button></div>` : `<button class="btn btn-dark btn-sm" type="button" data-quantity-id="${item.id}" data-change="1">Add</button>`}</div></article>`).join("")}</section></div>`).join(""); }
searchInput.addEventListener("input", renderMenuPage); filtersContainer.addEventListener("click", (event) => { const button = event.target.closest("[data-category]"); if (button) { activeCategory = button.dataset.category; renderMenuPage(); } }); menuContainer.addEventListener("click", (event) => { const button = event.target.closest("[data-quantity-id]"); if (button) { changeCartQuantity(button.dataset.quantityId, Number(button.dataset.change)); return; } const itemElement = event.target.closest(".menu-item"); if (!itemElement || !menuModal) return; const item = getMenuItems().find((entry) => entry.id === itemElement.dataset.itemId); if (!item) return; modalItemId = item.id; selectedModalOptions = {}; document.querySelector("#menu-modal-image").src = item.image || ""; document.querySelector("#menu-modal-image").alt = item.name; document.querySelector("#menu-modal-category").textContent = item.category; document.querySelector("#menu-item-modal-title").textContent = item.name; document.querySelector("#menu-modal-description").textContent = item.description; document.querySelector("#menu-modal-rating").textContent = `Rating ${Number(item.rating || 4.7).toFixed(1)}`; document.querySelector("#menu-modal-time").textContent = item.prepTime || "10 min"; document.querySelector("#menu-modal-price").textContent = formatCurrency(item.price); menuModal.show(); }); document.querySelector("#menu-modal-add")?.addEventListener("click", () => { changeCartQuantity(modalItemId, 1, selectedModalOptions); menuModal?.hide(); }); setupCustomisationPanel(); renderMenuPage(); window.addEventListener("cafe-creme-menu-ready", renderMenuPage);
